### ISSUE TITLE
windows部署报错

### ISSUE THREAD

**Issue by sunshuai12** [CarltonHere/auto-cpdaily#16]
依赖都安装了
版本：Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit
(AMD64)] on win32
报错代码：
Traceback (most recent call last):
  File "index.py", line 105, in <module>
    main()
  File "index.py", line 12, in main
    Utils.log("自动化任务开始执行")
  File "C:\Users\Administrator\Desktop\1\actions\Utils.py", line 131, in log
    (Utils.getYmlConfig()['Version'], content))
  File "C:\Users\Administrator\Desktop\1\actions\Utils.py", line 43, in getYmlCo
nfig
    config = yaml.load(file_data, Loader=yaml.FullLoader)
  File "C:\Users\Administrator\Desktop\1\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "C:\Users\Administrator\Desktop\1\yaml\constructor.py", line 49, in get_s
ingle_data
    node = self.get_single_node()
  File "C:\Users\Administrator\Desktop\1\yaml\composer.py", line 36, in get_sing
le_node
    document = self.compose_document()
  File "C:\Users\Administrator\Desktop\1\yaml\composer.py", line 55, in compose_
document
    node = self.compose_node(None, None)
  File "C:\Users\Administrator\Desktop\1\yaml\composer.py", line 84, in compose_
node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\Administrator\Desktop\1\yaml\composer.py", line 127, in compose
_mapping_node
    while not self.check_event(MappingEndEvent):
  File "C:\Users\Administrator\Desktop\1\yaml\parser.py", line 98, in check_even
t
    self.current_event = self.state()
  File "C:\Users\Administrator\Desktop\1\yaml\parser.py", line 439, in parse_blo
ck_mapping_key
    "expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block mapping
  in "<unicode string>", line 5, column 1:
    Version: 1.7.0
    ^
expected <block end>, but found '<block sequence start>'
  in "<unicode string>", line 48, column 5:
        - user:
        ^

**Comment by CarltonHere** [comment]
您好，请您认真编辑配置文件使其保持yaml规范
