### ISSUE TITLE
Error:list index out of range

### ISSUE THREAD

**Issue by GAFGripen** [CarltonHere/auto-cpdaily#25]
收集任务时出现Error:list index out of range
Traceback (most recent call last):
  File "/root/auto-cpdaily/index.py", line 105, in <module>
    main()
  File "/root/auto-cpdaily/index.py", line 22, in main
    msg = working(user, httpProxy)
  File "/root/auto-cpdaily/index.py", line 65, in working
    collection.fillForm()
  File "/root/auto-cpdaily/actions/collection.py", line 72, in fillForm
    userForm = self.userInfo['forms'][index]['form']
IndexError: list index out of range

**Comment by GAFGripen** [comment]
Solved.
一项''isRequired'项目仅在选择某一特定项目时发生，发现后改正
