### ISSUE TITLE
报错误信息 

### ISSUE THREAD

**Issue by q1226189767** [CarltonHere/auto-cpdaily#30]
list  index out of range  该怎么解决

**Comment by CarltonHere** [comment]
您好，请提供完整日志

**Comment by q1226189767** [comment]
服务器(V1.8.1)于2022-03-13 17:00:56尝试签到失败! 错误信息:list index out of range

**Comment by CarltonHere** [comment]
请将config.yml中的顶部debug改为true后复制完整日志

**Comment by Echo373** [comment]
Traceback (most recent call last):
  File "C:\Users\86134\OneDrive\桌面\auto-cpdaily-main\index.py", line 105, in <module>
    main()
  File "C:\Users\86134\OneDrive\桌面\auto-cpdaily-main\index.py", line 22, in main
    msg = working(user, httpProxy)
  File "C:\Users\86134\OneDrive\桌面\auto-cpdaily-main\index.py", line 65, in working
    collection.fillForm()
  File "C:\Users\86134\OneDrive\桌面\auto-cpdaily-main\actions\collection.py", line 72, in fillForm
    userForm = self.userInfo['forms'][index]['form']
IndexError: list index out of range

**Comment by Echo373** [comment]
> 复制更新配置日志.yml中的顶部调试改为true后复制完整日志
Traceback (most recent call last):
  File "C:\Users\86134\OneDrive\桌面\auto-cpdaily-main\index.py", line 105, in <module>
    main()
  File "C:\Users\86134\OneDrive\桌面\auto-cpdaily-main\index.py", line 22, in main
    msg = working(user, httpProxy)
  File "C:\Users\86134\OneDrive\桌面\auto-cpdaily-main\index.py", line 65, in working
    collection.fillForm()
  File "C:\Users\86134\OneDrive\桌面\auto-cpdaily-main\actions\collection.py", line 72, in fillForm
    userForm = self.userInfo['forms'][index]['form']
IndexError: list index out of range

**Comment by CarltonHere** [comment]
您好，请检查您的config.yml文件下forms与form结构是否完整，具体参考标准文件模板
