### ISSUE TITLE
河池学院无法登录

### ISSUE THREAD

**Issue by Xiaoshiguang520** [CarltonHere/auto-cpdaily#40]
提示报错
Traceback (most recent call last):
  File "C:\Users\xiaos\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\xiaos\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\xiaos\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\xiaos\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1349, in getresponse
    response.begin()
  File "C:\Users\xiaos\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "C:\Users\xiaos\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 285, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xiaos\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\xiaos\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\xiaos\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\xiaos\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\xiaos\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\xiaos\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\xiaos\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\xiaos\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1349, in getresponse
    response.begin()
  File "C:\Users\xiaos\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "C:\Users\xiaos\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 285, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Download\auto-cpdaily-main\index.py", line 105, in <module>
    main()
  File "E:\Download\auto-cpdaily-main\index.py", line 22, in main
    msg = working(user, httpProxy)
  File "E:\Download\auto-cpdaily-main\index.py", line 56, in working
    wise.login()
  File "E:\Download\auto-cpdaily-main\actions\wiseLoginService.py", line 92, in login
    self.getLoginUrlBySchoolName()
  File "E:\Download\auto-cpdaily-main\actions\wiseLoginService.py", line 66, in getLoginUrlBySchoolName
    res = self.session.get(clientUrl, verify=False)
  File "C:\Users\xiaos\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\xiaos\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\xiaos\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 677, in send
    history = [resp for resp in gen]
  File "C:\Users\xiaos\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "C:\Users\xiaos\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 237, in resolve_redirects
    resp = self.send(
  File "C:\Users\xiaos\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\xiaos\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by CarltonHere** [comment]
您好，您是开启系统代理了吗

**Comment by Xiaoshiguang520** [comment]
> 您好，您是开启系统代理了吗

没有开启代理，我尝试过开启代理和不开启代理都是一样。

**Comment by CarltonHere** [comment]
您好，请检查网络环境，经测试河池学院登录正常
