### ISSUE TITLE
请求适配配置项手写签名

### ISSUE THREAD

**Issue by Weske5** [CarltonHere/auto-cpdaily#45]
2022-04-15 12:05:46 V1.8.6 Error:[
第12个配置项的类型未适配]
Traceback (most recent call last):
  File "index.py", line 23, in main
    msg = working(user, httpProxy)
  File "index.py", line 65, in working
    collection.fillForm()
  File "/root/auto-cpdaily/actions/collection.py", line 146, in fillForm
    raise Exception(f'\r\n第{index + 1}个配置项的类型未适配')
Exception: 
第12个配置项的类型未适配

图片如下：
![手写签名](https://s2.loli.net/2022/04/15/9yAzLYukhV6N8Tx.jpg)

**Comment by CarltonHere** [comment]
您好，请使用最新版测试并提供日志，同时希望你能留下联系方式以便沟通细节

**Comment by Maxmumu** [comment]
请问是如何解决的?保存到本地，像健康码那样，按照图片方式提交吗
