### ISSUE TITLE
Error:'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by luckInkHin** [CarltonHere/auto-cpdaily#6]
2021-11-09 00:31:53 V1.6.0 10s后开始执行用户**********的任务
2021-11-09 00:32:03 V1.6.0 正在获取登录地址
2021-11-09 00:32:03 V1.6.0 开始尝试登录账号
2021-11-09 00:32:08 V1.6.0 开始执行收集任务
2021-11-09 00:33:38 V1.6.0 Error:'NoneType' object is not subscriptable
2021-11-09 00:33:38 V1.6.0 该用户未配置推送,已取消发送！

经过多次尝试，该脚本仍然不起作用，似乎报错在 collection.py的line 43: self.schoolTaskWid = res['datas']['collector']['schoolTaskWid'] 这一条语句，大意是不存在schoolTaskWid，或者是说它无效。我并不了解这代表什么。
我很想找到答案，通过Google不断翻找，终于在一个快照链接，我了解到另一位曾经分支的开发者 显然他在十月28日已经注意到了这个问题，但是我已经无法找到该作者的github，仓库页面也处在404 NotPages，而另一边几乎所有的联系方式都指向了子墨的讨论群，但其已经设置为了禁止入群。
现在我非常苦恼，该如何解决他，再入睡之前再翻了一遍github，发现您commit于3 hours ago，于是提交了这个issues，希望能得到您的帮助。（痛哭o(╥﹏╥)o）

我的配置院校是广工贸。

![image](https://user-images.githubusercontent.com/63509561/140783118-fbbf5b5f-fc2e-41ef-b63f-a466e8aeee51.png)
来源：https://webcache.googleusercontent.com/search?q=cache:qeAFsVL8lz4J:https://githubmemory.com/index.php/%40thriving123+&cd=2&hl=zh-CN&ct=clnk

**Comment by CarltonHere** [comment]
很抱歉，我这边没有复现该问题，请重新拉取仓库再试。如果仍有该问题，请留下联系方式

**Comment by luckInkHin** [comment]
o(╥﹏╥)o今天已经错过信息收集了，明天早上我再测试。

**Comment by luckInkHin** [comment]
！！重新拉取修改yaml后，它完美的通过了异常！！！！
`PS C:\Users\Ink\Desktop\auto-cpdaily-main> Python index.py
2021-11-10 07:44:32 V1.6.0 自动化任务开始执行
2021-11-10 07:44:32 V1.6.0 10s后开始执行用户************的任务
2021-11-10 07:44:42 V1.6.0 正在获取登录地址
2021-11-10 07:44:42 V1.6.0 开始尝试登录账号
2021-11-10 07:44:45 V1.6.0 开始执行收集任务
Traceback (most recent call last):
  File "C:\Users\Ink\Desktop\auto-cpdaily-main\index.py", line 117, in <module>
    main()
  File "C:\Users\Ink\Desktop\auto-cpdaily-main\index.py", line 23, in main
    msg = working(user, httpProxy)
  File "C:\Users\Ink\Desktop\auto-cpdaily-main\index.py", line 66, in working
    collection.fillForm()
  File "C:\Users\Ink\Desktop\auto-cpdaily-main\actions\collection.py", line 71, in fillForm
    userForm = self.userInfo['forms'][index]['form']
KeyError: 'forms'
PS C:\Users\Ink\Desktop\auto-cpdaily-main> Python index.py
2021-11-10 07:49:19 V1.6.0 自动化任务开始执行
2021-11-10 07:49:19 V1.6.0 10s后开始执行用户************的任务
2021-11-10 07:49:29 V1.6.0 正在获取登录地址
2021-11-10 07:49:30 V1.6.0 开始尝试登录账号
2021-11-10 07:49:32 V1.6.0 开始执行收集任务
2021-11-10 07:49:34 V1.6.0 正在加密表单数据
2021-11-10 07:49:34 V1.6.0 正在尝试提交数据
2021-11-10 07:49:34 V1.6.0 自动化任务执行完毕
PS C:\Users\Ink\Desktop\auto-cpdaily-main>`

**Comment by CarltonHere** [comment]
已解决
