### ISSUE TITLE
您无权获取工作日志列表

### ISSUE THREAD

**Issue by Hades-001** [CarltonHere/auto-cpdaily#7]
2021-11-20 17:48:02 V1.6.0 自动化任务开始执行
2021-11-20 17:48:02 V1.6.0 10s后开始执行用户的任务
2021-11-20 17:48:12 V1.6.0 正在获取登录地址
2021-11-20 17:48:12 V1.6.0 开始尝试登录账号
2021-11-20 17:48:15 V1.6.0 开始执行日志任务
Traceback (most recent call last):
  File "index.py", line 117, in <module>
    main()
  File "index.py", line 23, in main
    msg = working(user, httpProxy)
  File "index.py", line 96, in working
    work.checkHasLog()
  File "/home/opensuse/auto-cpdaily-main/actions/workLog.py", line 28, in checkHasLog
    raise Exception('您无权获取工作日志列表')
Exception: 您无权获取工作日志列表

这个情况有办法解决吗？

**Comment by CarltonHere** [comment]
非项目代码问题，不做处理
