### ISSUE TITLE
打卡出错

### ISSUE THREAD

**Issue by hhhllll888** [CarltonHere/auto-cpdaily#70]
之前用自己手机打卡打了几次，然后用自己旧手机打卡，自己同学的表单没出问题，我自己的表单出问题了，有谁能方便看下吗
敏感信息隐藏了
```
2022-09-02 00:03:08 V1.9.0 自动化任务开始执行
2022-09-02 00:03:08 V1.9.0 10s后开始执行用户2021xxxxxxxxx的任务
2022-09-02 00:03:14 V1.9.0 正在获取登录地址
2022-09-02 00:03:14 V1.9.0 开始尝试登录账号
2022-09-02 00:03:26 V1.9.0 开始执行收集任务
2022-09-02 00:03:33 V1.9.0 Error:[Expecting value: line 1 column 1 (char 0)]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/auto/index.py", line 23, in main
    msg = working(user, httpProxy)
  File "/data/data/com.termux/files/home/auto/index.py", line 64, in working
    collection.queryForm()
  File "/data/data/com.termux/files/home/auto/actions/collection.py", line 63, in queryForm
    verify=False).json()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/data/data/com.termux/files/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/data/data/com.termux/files/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

2022-09-02 00:03:35 V1.9.0 APPRISE推送消息成功
2022-09-02 00:03:35 V1.9.0 10s后开始执行用户2021xxxxxxxxx的任务
2022-09-02 00:03:41 V1.9.0 正在获取登录地址
2022-09-02 00:03:41 V1.9.0 开始尝试登录账号
2022-09-02 00:03:47 V1.9.0 开始执行收集任务
2022-09-02 00:03:50 V1.9.0 正在加密表单数据
2022-09-02 00:03:50 V1.9.0 正在尝试提交数据
2022-09-02 00:03:51 V1.9.0 SUCCESS
2022-09-02 00:03:53 V1.9.0 APPRISE推送消息成功
2022-09-02 00:03:54 V1.9.0 自动化任务执行完毕
```

**Comment by hhhllll888** [comment]
出现这个后，第二次打卡又会成功

**Comment by hhhllll888** [comment]
手机性能不足
